/*
ALGUNAS FUNCIONES NO TIENEN PARAMETROS PERO TIENEN RETORNO,
SON USADAS GENERALMENTE PARA FORMATEAR MENSAJES, CAMBIAR
ESTADOS DE UNA VARIABLE ENTRE OTROS.
*/
let PI = 3.1416;

function valorPi(params) {
    return PI;
}

let resultadoPI = valorPi();
console.log(resultadoPI);
